# Use the official Node.js 10 image as the base image
FROM node:10

# Create a directory for the app
RUN mkdir -p /usr/src/app

# Set the working directory to the app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json /usr/src/app/
RUN npm install

# Copy the app code to the working directory
COPY . /usr/src/app

# Expose the app's port
EXPOSE 3000

# Run the app
CMD ["npm", "start"]
